name: Publish NuGet

on:
  workflow_call:
    inputs: 
      dotnet-version:
        required: false 
        type: string

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:        
      - name: ⬇️ Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: nuget-package
          path: ./artifacts

      - name: 🔧 Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: 🚚 Publish to NuGet
        run: dotnet nuget push "./artifacts/*.nupkg" \
              --api-key ${{ secrets.NUGET_API_KEY }} \
              --source https://api.nuget.org/v3/index.json