name: Publish NuGet

on:
  workflow_call:
    inputs: 
      dotnet-version:
        required: false 
        type: string

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:        
      - name: ⬇️ Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: nuget-package
          path: .

      - name: 🔧 Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: 🚚 Publishing NuGet
        shell: pwsh
        run: |
          $packages = Get-ChildItem -Path . -Filter *.nupkg
          $source = "nuget.org"

          foreach ($pkg in $packages) {
            "Publishing $($pkg.FullName) to $source"

            dotnet nuget push `
              $pkg.FullName `
              --api-key $env:NUGET_API_KEY `
              --source $source `
              --skip-duplicate
          }