name: 👩🏻‍🔬 Test

on:
  workflow_call:
    inputs: 
      dotnet-version:
        required: true 
        type: string
      tests:
        required: true
        type: string
        description: 'JSON array of test names'

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.collect.outputs.projects }}
    steps:
      - name: 🗃️ Checkout
        uses: actions/checkout@v4

      - name: 🔍 Discover Test Projects
        id: collect
        run: |
          projects=$(find . -name "*Tests.csproj" | jq -R -s -c 'split("\n")[:-1] | map({filename: (. | split("/") | last | sub("\\.csproj$"; "")), path: .})')
          echo "projects=$projects" >> $GITHUB_OUTPUT

  test:
    needs: discover
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJson(needs.discover.outputs.projects) }}
    
    steps:
    - name: 🗃️ Checkout
      uses: actions/checkout@v4

    - name: 🔧 Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: 🔄 Restore
      working-directory: src
      run: dotnet restore
    
    - name: 👩🏻‍🔬 Run ${{ matrix.project.filename }}
      run: dotnet run --project ${{ matrix.project.path }} --configuration Release --report-trx
    
    - name: 📢 Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: (!cancelled())
      with:
        files: tests/**/*.trx
