<Project Sdk="Microsoft.NET.Sdk">

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ Documentation                                                        │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <PropertyGroup>
      <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ Analyzer Settings                                                    │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <PropertyGroup>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WB.CodeAnalyzer">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ Source Link.                                                         │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
  </ItemGroup>
  
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <EnableSourceLink>true</EnableSourceLink>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <EnableSourceLink>false</EnableSourceLink>
    <PublishRepositoryUrl>false</PublishRepositoryUrl>
    <EmbedUntrackedSources>false</EmbedUntrackedSources>
  </PropertyGroup>

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
	     │ Deterministic Builds                                                 │
	     ╰──────────────────────────────────────────────────────────────────────╯ -->
	<PropertyGroup Condition="'$(Configuration)'=='Release'">
	    <Deterministic>true</Deterministic>
	    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
	    <Deterministic>false</Deterministic>
	    <ContinuousIntegrationBuild>false</ContinuousIntegrationBuild>
	</PropertyGroup>

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ Debug Settings                                                       │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <PropertyGroup>
      <DebugType>portable</DebugType>
      <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ Documentation                                                        │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ SourceLink                                                           │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <ItemGroup> 
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <EnableSourceLink>false</EnableSourceLink>
    <PublishRepositoryUrl>false</PublishRepositoryUrl>
    <EmbedUntrackedSources>false</EmbedUntrackedSources>
  </PropertyGroup>

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ Package References                                                   │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <ItemGroup Condition="'$(SourceBuild)' != 'true'">
  </ItemGroup>

  <!-- ╭──────────────────────────────────────────────────────────────────────╮
       │ Project References                                                   │
       ╰──────────────────────────────────────────────────────────────────────╯ -->
  <ItemGroup Condition="'$(SourceBuild)' == 'true'">
  </ItemGroup>

</Project>
