name: Publish NuGet

on:
  workflow_call:
    inputs: 
      dotnet-version:
        required: false 
        type: string

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:        
      - name: ⬇️ Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: nuget-package
          path: .

      - name: 🔧 Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: 🔧 Reset NuGet sources
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          echo "Clearing all NuGet sources..."
          dotnet nuget list source | tail -n +3 | awk '{print $2}' | while read src; do
            echo "Removing source: $src"
            dotnet nuget remove source "$src" || true
          done

          echo "Adding new NuGet source: nuget.org"
          dotnet nuget add source "https://api.nuget.org/v3/index.json" \
            --name "nuget.org" \
            --username "apikey" \
            --password "$NUGET_API_KEY" \
            --store-password-in-clear-text

      - name: 🚚 Publishing NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          packages=$(find . -name "*.nupkg")

          for package in $packages; do
            echo "Publishing $package to $source"

            dotnet nuget push "$package" --source nuget.org --skip-duplicate
          done