name: Publish NuGet

on:
  workflow_call:
    inputs: 
      dotnet-version:
        required: false 
        type: string

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:        
      - name: ⬇️ Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: nuget-package
          path: .

      - name: 🔧 Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: 🚚 Publishing NuGet
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
        run: |
          packages=$(find . -name "*.nupkg")

          for package in $packages; do
            echo "Publishing $package to nuget.org"

            dotnet nuget push "$package"
          done